Try to fix build by switching to older version (used in pyzo)
Now, the build fails with:
```bash
  Running setup.py install for django-allauth ... done
  Running setup.py install for django-compat ... done
  Running setup.py install for django-background-tasks ... done
  Running setup.py install for django-sass-processor ... done
  Running setup.py install for args ... done
  Running setup.py install for clint ... done
  Running setup.py install for pynacl ... done
  Running setup.py install for python-vagrant ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for fdroidserver ... done
  Running setup.py install for rjsmin ... done
  Running setup.py install for rcssmin ... done
  Running setup.py install for django-hvad ... done
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/app/lib/python3.5/site-packages/sip.so'
You are using pip version 8.1.2, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Error: module repomaker: Child process exited with code 2
```